# **What is Pandas?**
***Pandas is a Python library used for working with, analyzing, and manipulating data.***

***Pandas helps us store, organize, clean, analyze, and process data easily in Python.***

# **Why is Pandas important?**
✔***Data organization – Easily work with rows and columns.***

✔***Data cleaning – Handle missing, duplicate, or incorrect data.***

✔***Data analysis – Calculate mean, maximum, minimum, correlation, etc.***

✔***Filtering & sorting – Quickly find and arrange specific data.***

✔***CSV/Excel handling – Read and write files such as .csv and Excel files.***

✔***Works with NumPy – Pandas is built on top of NumPy and works very well with it.***

✔***Very important for AI/ML – Before training a machine-learning model, data usually needs to be loaded, cleaned, explored, and prepared. Pandas is one of the main tools for this.***

# **Series:**
***A Series is a one-dimensional labeled array in Pandas.***

In [1]:
import pandas as pd
# Create a Series:
s=pd.Series([10,20,30,40,50,60],index=['a','b','c','d','e','f'])
print(s)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [2]:
# index vs values:
print("values: ",s.values)
print("indexes: ",s.index)
print("data_type: ",s.dtype)

values:  [10 20 30 40 50 60]
indexes:  Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='str')
data_type:  int64

In [3]:
print(s.head(3))   # first three values

a    10
b    20
c    30
dtype: int64

In [4]:
print(s.tail(3)) # last three values

d    40
e    50
f    60
dtype: int64

In [5]:
print(s.value_counts())  # count occurance of values

10    1
20    1
30    1
40    1
50    1
60    1
Name: count, dtype: int64

# **DataFrame:**
***A DataFrame is a two-dimensional labeled data structure consisting of rows and columns.***

In [6]:
# Create a DataFrame:
data={"name":["Mohsin Ali","Kamran Khan","Sohail Ahmed","Rehan Ali","M Talha","M Zubair"],
      "age": [23,34,54,65,22,34],
      "city":["Nawab Shah","Dadu","Sukkur","Mirpurkhas","Hyderabad","Nawabshah"]}
df=pd.DataFrame(data)

In [7]:
print(df)

           name  age        city
0    Mohsin Ali   23  Nawab Shah
1   Kamran Khan   34        Dadu
2  Sohail Ahmed   54      Sukkur
3     Rehan Ali   65  Mirpurkhas
4       M Talha   22   Hyderabad
5      M Zubair   34   Nawabshah

In [8]:
# Load sample csv:'
df=pd.read_csv('friends_index_false.csv')
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   marks   4 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 292.0 bytes
None

In [9]:
# Shape and data type:
print(df.shape)         # rows and columns
print(df.dtypes)

(4, 3)
name       str
marks    int64
city       str
dtype: object

# **Statistical Summary:**

In [10]:
print(df.describe())

           marks
count   4.000000
mean   55.750000
std     6.946222
min    51.000000
25%    51.750000
50%    53.000000
75%    57.000000
max    66.000000

In [11]:
# Labled based selection:
subset_loc=df.loc[1:3,["name","city"]]
print(subset_loc)

      name         city
1  M Azhar    Hyderabad
2    Saqib       Sukkur
3   Raheel  Mirpurekhas

In [12]:
# Integer based selection:
subset_iloc=df.iloc[1:3,0:3]  # access subset of dataframe using indices
print(subset_iloc)

      name  marks       city
1  M Azhar     52  Hyderabad
2    Saqib     51     Sukkur

In [13]:
df=pd.read_csv('employs_record.csv')
print(df.columns)

Index(['emp_id', 'name', 'age', 'department', 'experience', 'salary', 'city',
       'performance_rating', 'bonus', 'total_sal', 'rank'],
      dtype='str')

In [14]:
# Boolean filtering:
high_sal=df[df['salary']>70000]
print(high_sal.loc[0:4,["name","department","salary","rank"]])

     name department    salary  rank
0    Saad         IT  150000.0     1
1   Usman         IT  140000.0     2
2  Farhan         HR  115000.0     3
3  Kashif  Marketing  110000.0     4
4   Komal         IT  102000.0     5

In [15]:
# Modify data using column lables:
df.loc[df["age"]<30, 'salary']=65000
print(df.loc[df['age']<30, ['name','salary']])

      name   salary
11   Hamza  65000.0
12  Danish  65000.0
13   Ahmed  65000.0
14    Nida  65000.0
15    Noor  65000.0
16    Hina  65000.0
17  Ayesha  65000.0
18     Ali  65000.0
19  Fatima  65000.0

In [16]:
!pip install openpyxl

Requirement already satisfied: openpyxl in H:\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in H:\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)

In [17]:
df=pd.read_csv('sales_data.csv')
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   20 non-null     str
 1   Product   20 non-null     str
 2   Category  20 non-null     str
 3   Cost      20 non-null     float64
 4   Quantity  20 non-null     int64
 5   Price     20 non-null     int64
 6   Revenue   20 non-null     int64
 7   Profit    20 non-null     float64
 8   City      20 non-null     str
 9   Date      20 non-null     str
 10  Month     20 non-null     str
 11  cost      0 non-null      float64
dtypes: float64(3), int64(3), str(6)
memory usage: 2.9 KB
None

# **Convert data type of column date from string to datetime:**

In [18]:
df["Date"]=pd.to_datetime(df["Date"])
print(df["Date"].dtype)

datetime64[us]

In [19]:
# Category data type: Used to store repeated values as category wise for efficient memory usage.
df[["Category","Product"]]=df[["Category","Product"]].astype("category")
print(df[["Category","Product"]].dtypes)

Category    category
Product     category
dtype: object

# **Covert DataFrame into excel file :**

df.to_excel('subset_sales.xlsx',sheet_name="Sales")
print("Done!")

# **Convert DataFrame into json file:**

In [20]:
df.to_json('subset_sales.json',
           orient="records",
           date_format="iso")
print("Done!")

Done!

In [21]:
# Create a new column:
df["cost"]=None

In [22]:
# Delete column:
df.drop(columns=["Cost"],inplace=True)

In [23]:
# insert column at specific index:
df.insert(3,"Cost",None)

In [24]:
print(df.columns)

Index(['OrderID', 'Product', 'Category', 'Cost', 'Quantity', 'Price',
       'Revenue', 'Profit', 'City', 'Date', 'Month', 'cost'],
      dtype='str')

In [25]:
df.drop(columns=["Revenue"],inplace=True)

In [26]:
df.insert(6,"Revenue",None)

In [27]:
df["Revenue"]=df["Price"]*df["Quantity"]

In [28]:
# Get unique values from a column:
print(df["Product"].unique())

['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Printer', 'Headphones']
Categories (6, str): ['Headphones', 'Keyboard', 'Laptop', 'Monitor', 'Mouse', 'Printer']

In [29]:
df["Cost"]=df["Price"]-df["Price"]*0.1

In [30]:
print(df[["Product","Cost","Price","Quantity","Revenue"]])

       Product     Cost  Price  Quantity  Revenue
0       Laptop  76500.0  85000         2   170000
1        Mouse   1080.0   1200         5     6000
2     Keyboard   2250.0   2500         3     7500
3      Monitor  27000.0  30000         1    30000
4      Printer  16200.0  18000         2    36000
5       Laptop  78300.0  87000         1    87000
6   Headphones   4050.0   4500         4    18000
7        Mouse   1080.0   1200         6     7200
8     Keyboard   2340.0   2600         2     5200
9      Monitor  26550.0  29500         3    88500
10     Printer  16650.0  18500         1    18500
11      Laptop  77400.0  86000         2   172000
12       Mouse   1125.0   1250         5     6250
13    Keyboard   2295.0   2550         4    10200
14  Headphones   4230.0   4700         2     9400
15     Monitor  27900.0  31000         2    62000
16     Printer  16380.0  18200         3    54600
17      Laptop  76950.0  85500         1    85500
18       Mouse   1170.0   1300         7     9100
19    Keyboard   2340.0   2600         5    13000

In [31]:
df.drop(columns=["Profit"],inplace=True)

In [32]:
df.insert(7,"Profit",(df["Revenue"]-(df["Cost"]*df["Quantity"])))

In [33]:
print(df[["Product","Cost","Price","Quantity","Revenue","Profit"]])

       Product     Cost  Price  Quantity  Revenue   Profit
0       Laptop  76500.0  85000         2   170000  17000.0
1        Mouse   1080.0   1200         5     6000    600.0
2     Keyboard   2250.0   2500         3     7500    750.0
3      Monitor  27000.0  30000         1    30000   3000.0
4      Printer  16200.0  18000         2    36000   3600.0
5       Laptop  78300.0  87000         1    87000   8700.0
6   Headphones   4050.0   4500         4    18000   1800.0
7        Mouse   1080.0   1200         6     7200    720.0
8     Keyboard   2340.0   2600         2     5200    520.0
9      Monitor  26550.0  29500         3    88500   8850.0
10     Printer  16650.0  18500         1    18500   1850.0
11      Laptop  77400.0  86000         2   172000  17200.0
12       Mouse   1125.0   1250         5     6250    625.0
13    Keyboard   2295.0   2550         4    10200   1020.0
14  Headphones   4230.0   4700         2     9400    940.0
15     Monitor  27900.0  31000         2    62000   6200.0
16     Printer  16380.0  18200         3    54600   5460.0
17      Laptop  76950.0  85500         1    85500   8550.0
18       Mouse   1170.0   1300         7     9100    910.0
19    Keyboard   2340.0   2600         5    13000   1300.0

In [34]:
df.to_csv('sales_data.csv',index=False)

In [35]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   20 non-null     str
 1   Product   20 non-null     category
 2   Category  20 non-null     category
 3   Cost      20 non-null     float64
 4   Quantity  20 non-null     int64
 5   Price     20 non-null     int64
 6   Revenue   20 non-null     int64
 7   Profit    20 non-null     float64
 8   City      20 non-null     str
 9   Date      20 non-null     datetime64[us]
 10  Month     20 non-null     str
 11  cost      0 non-null      object
dtypes: category(2), datetime64[us](1), float64(2), int64(3), object(1), str(3)
memory usage: 2.2+ KB
None

In [36]:
df.loc[3,"Quantity"]=None
df.loc[6,"Quantity"]=None
df.loc[12,"Revenue"]=None
df.loc[9,"Revenue"]=None
df.loc[15,"Revenue"]=None

In [37]:
print(df.isna().sum())

OrderID      0
Product      0
Category     0
Cost         0
Quantity     2
Price        0
Revenue      3
Profit       0
City         0
Date         0
Month        0
cost        20
dtype: int64

In [38]:
# Change column data type to numeric data type:
df["Quantity"]=pd.to_numeric(df["Quantity"])
df["Revenue"]=pd.to_numeric(df["Revenue"])

# **Dealing with missing values:**

In [39]:
# fill missing values with mean value:
df["Quantity"]=df["Quantity"].fillna(df["Quantity"].mean())

In [40]:
#  fill missing values with mean value:
df["Revenue"]=df["Revenue"].fillna(df["Revenue"].mean())

In [41]:
print(df["Revenue"].mean())
print(df["Quantity"].mean())

43482.35294117647
3.111111111111111

In [42]:
print(df.info)

<bound method DataFrame.info of    OrderID     Product     Category     Cost  Quantity  Price        Revenue  \
0   ORD001      Laptop  Electronics  76500.0  2.000000  85000  170000.000000
1   ORD002       Mouse  Accessories   1080.0  5.000000   1200    6000.000000
2   ORD003    Keyboard  Accessories   2250.0  3.000000   2500    7500.000000
3   ORD004     Monitor  Electronics  27000.0  3.111111  30000   30000.000000
4   ORD005     Printer  Electronics  16200.0  2.000000  18000   36000.000000
5   ORD006      Laptop  Electronics  78300.0  1.000000  87000   87000.000000
6   ORD007  Headphones  Accessories   4050.0  3.111111   4500   18000.000000
7   ORD008       Mouse  Accessories   1080.0  6.000000   1200    7200.000000
8   ORD009    Keyboard  Accessories   2340.0  2.000000   2600    5200.000000
9   ORD010     Monitor  Electronics  26550.0  3.000000  29500   43482.352941
10  ORD011     Printer  Electronics  16650.0  1.000000  18500   18500.000000
11  ORD012      Laptop  Electronics  77400.0  2.000000  86000  172000.000000
12  ORD013       Mouse  Accessories   1125.0  5.000000   1250   43482.352941
13  ORD014    Keyboard  Accessories   2295.0  4.000000   2550   10200.000000
14  ORD015  Headphones  Accessories   4230.0  2.000000   4700    9400.000000
15  ORD016     Monitor  Electronics  27900.0  2.000000  31000   43482.352941
16  ORD017     Printer  Electronics  16380.0  3.000000  18200   54600.000000
17  ORD018      Laptop  Electronics  76950.0  1.000000  85500   85500.000000
18  ORD019       Mouse  Accessories   1170.0  7.000000   1300    9100.000000
19  ORD020    Keyboard  Accessories   2340.0  5.000000   2600   13000.000000

     Profit       City       Date     Month  cost
0   17000.0    Karachi 2026-01-05   January  None
1     600.0  Hyderabad 2026-01-08   January  None
2     750.0     Lahore 2026-01-10   January  None
3    3000.0    Karachi 2026-02-03  February  None
4    3600.0  Islamabad 2026-02-08  February  None
5    8700.0    Karachi 2026-02-15  February  None
6    1800.0  Hyderabad 2026-03-01     March  None
7     720.0     Lahore 2026-03-04     March  None
8     520.0     Sukkur 2026-03-10     March  None
9    8850.0  Islamabad 2026-04-02     April  None
10   1850.0    Karachi 2026-04-15     April  None
11  17200.0  Hyderabad 2026-05-01       May  None
12    625.0     Lahore 2026-05-06       May  None
13   1020.0     Sukkur 2026-05-20       May  None
14    940.0    Karachi 2026-06-02      June  None
15   6200.0  Islamabad 2026-06-18      June  None
16   5460.0  Hyderabad 2026-07-05      July  None
17   8550.0     Lahore 2026-07-15      July  None
18    910.0    Karachi 2026-08-01    August  None
19   1300.0     Sukkur 2026-08-20    August  None  >

In [43]:
df.loc[3,"Quantity"]=None
df.loc[6,"Quantity"]=None
df.loc[12,"Revenue"]=None
df.loc[9,"Revenue"]=None
df.loc[15,"Revenue"]=None

In [44]:
# fill missing values with midian:
df["Quantity"]=df["Quantity"].fillna(df["Quantity"].median())
print(df["Quantity"].median())

2.5

In [45]:
#  fill missing values with mode:
df["Revenue"]=df["Revenue"].fillna(df["Revenue"].mode())
print(df["Revenue"].mode())

0     18500.0
1     54600.0
2    170000.0
Name: Revenue, dtype: float64

In [46]:
print(df.info)

<bound method DataFrame.info of    OrderID     Product     Category     Cost  Quantity  Price   Revenue  \
0   ORD001      Laptop  Electronics  76500.0       2.0  85000  170000.0
1   ORD002       Mouse  Accessories   1080.0       5.0   1200    6000.0
2   ORD003    Keyboard  Accessories   2250.0       3.0   2500    7500.0
3   ORD004     Monitor  Electronics  27000.0       2.5  30000   30000.0
4   ORD005     Printer  Electronics  16200.0       2.0  18000   36000.0
5   ORD006      Laptop  Electronics  78300.0       1.0  87000   87000.0
6   ORD007  Headphones  Accessories   4050.0       2.5   4500   18000.0
7   ORD008       Mouse  Accessories   1080.0       6.0   1200    7200.0
8   ORD009    Keyboard  Accessories   2340.0       2.0   2600    5200.0
9   ORD010     Monitor  Electronics  26550.0       3.0  29500   18500.0
10  ORD011     Printer  Electronics  16650.0       1.0  18500   18500.0
11  ORD012      Laptop  Electronics  77400.0       2.0  86000  172000.0
12  ORD013       Mouse  Accessories   1125.0       5.0   1250   54600.0
13  ORD014    Keyboard  Accessories   2295.0       4.0   2550   10200.0
14  ORD015  Headphones  Accessories   4230.0       2.0   4700    9400.0
15  ORD016     Monitor  Electronics  27900.0       2.0  31000  170000.0
16  ORD017     Printer  Electronics  16380.0       3.0  18200   54600.0
17  ORD018      Laptop  Electronics  76950.0       1.0  85500   85500.0
18  ORD019       Mouse  Accessories   1170.0       7.0   1300    9100.0
19  ORD020    Keyboard  Accessories   2340.0       5.0   2600   13000.0

     Profit       City       Date     Month  cost
0   17000.0    Karachi 2026-01-05   January  None
1     600.0  Hyderabad 2026-01-08   January  None
2     750.0     Lahore 2026-01-10   January  None
3    3000.0    Karachi 2026-02-03  February  None
4    3600.0  Islamabad 2026-02-08  February  None
5    8700.0    Karachi 2026-02-15  February  None
6    1800.0  Hyderabad 2026-03-01     March  None
7     720.0     Lahore 2026-03-04     March  None
8     520.0     Sukkur 2026-03-10     March  None
9    8850.0  Islamabad 2026-04-02     April  None
10   1850.0    Karachi 2026-04-15     April  None
11  17200.0  Hyderabad 2026-05-01       May  None
12    625.0     Lahore 2026-05-06       May  None
13   1020.0     Sukkur 2026-05-20       May  None
14    940.0    Karachi 2026-06-02      June  None
15   6200.0  Islamabad 2026-06-18      June  None
16   5460.0  Hyderabad 2026-07-05      July  None
17   8550.0     Lahore 2026-07-15      July  None
18    910.0    Karachi 2026-08-01    August  None
19   1300.0     Sukkur 2026-08-20    August  None  >

In [47]:
df.loc[3,"City"]=None
df.loc[6,"City"]=None

In [48]:
# Instead of filling missing values simply drop them :
df.dropna(subset=["City"],inplace = True)

In [49]:
print(df.info)

<bound method DataFrame.info of    OrderID     Product     Category     Cost  Quantity  Price   Revenue  \
0   ORD001      Laptop  Electronics  76500.0       2.0  85000  170000.0
1   ORD002       Mouse  Accessories   1080.0       5.0   1200    6000.0
2   ORD003    Keyboard  Accessories   2250.0       3.0   2500    7500.0
4   ORD005     Printer  Electronics  16200.0       2.0  18000   36000.0
5   ORD006      Laptop  Electronics  78300.0       1.0  87000   87000.0
7   ORD008       Mouse  Accessories   1080.0       6.0   1200    7200.0
8   ORD009    Keyboard  Accessories   2340.0       2.0   2600    5200.0
9   ORD010     Monitor  Electronics  26550.0       3.0  29500   18500.0
10  ORD011     Printer  Electronics  16650.0       1.0  18500   18500.0
11  ORD012      Laptop  Electronics  77400.0       2.0  86000  172000.0
12  ORD013       Mouse  Accessories   1125.0       5.0   1250   54600.0
13  ORD014    Keyboard  Accessories   2295.0       4.0   2550   10200.0
14  ORD015  Headphones  Accessories   4230.0       2.0   4700    9400.0
15  ORD016     Monitor  Electronics  27900.0       2.0  31000  170000.0
16  ORD017     Printer  Electronics  16380.0       3.0  18200   54600.0
17  ORD018      Laptop  Electronics  76950.0       1.0  85500   85500.0
18  ORD019       Mouse  Accessories   1170.0       7.0   1300    9100.0
19  ORD020    Keyboard  Accessories   2340.0       5.0   2600   13000.0

     Profit       City       Date     Month  cost
0   17000.0    Karachi 2026-01-05   January  None
1     600.0  Hyderabad 2026-01-08   January  None
2     750.0     Lahore 2026-01-10   January  None
4    3600.0  Islamabad 2026-02-08  February  None
5    8700.0    Karachi 2026-02-15  February  None
7     720.0     Lahore 2026-03-04     March  None
8     520.0     Sukkur 2026-03-10     March  None
9    8850.0  Islamabad 2026-04-02     April  None
10   1850.0    Karachi 2026-04-15     April  None
11  17200.0  Hyderabad 2026-05-01       May  None
12    625.0     Lahore 2026-05-06       May  None
13   1020.0     Sukkur 2026-05-20       May  None
14    940.0    Karachi 2026-06-02      June  None
15   6200.0  Islamabad 2026-06-18      June  None
16   5460.0  Hyderabad 2026-07-05      July  None
17   8550.0     Lahore 2026-07-15      July  None
18    910.0    Karachi 2026-08-01    August  None
19   1300.0     Sukkur 2026-08-20    August  None  >

# **String and text cleaning:**

In [50]:
import pandas as pd

data = {
    "Name": ["  Ali  ", "AHMED", "sara", "  zain khan", "FATIMA  "],
    "City": [" karachi", "LAHORE ", "  Islamabad  ", "karachi", " ISLAMABAD"],
    "Email": ["ali@gmail.com ", " AHMED@GMAIL.COM", "sara@gmail.com", "zain @gmail.com", "fatima@gmail.com "],
    "Phone": ["0300-1234567", "0312 9876543", "0333-5556666", "0345  1112233", "0301-9998888"]
}

df = pd.DataFrame(data)

print(df)

          Name           City              Email          Phone
0        Ali          karachi     ali@gmail.com    0300-1234567
1        AHMED        LAHORE     AHMED@GMAIL.COM   0312 9876543
2         sara    Islamabad       sara@gmail.com   0333-5556666
3    zain khan        karachi    zain @gmail.com  0345  1112233
4     FATIMA        ISLAMABAD  fatima@gmail.com    0301-9998888

In [51]:
df["Name"] = df["Name"].str.strip()    # remove unnecessory spaces
print(df["Name"])

0          Ali
1        AHMED
2         sara
3    zain khan
4       FATIMA
Name: Name, dtype: str

In [52]:
df["Name"]=df["Name"].str.lower()      # convert all strings into lowercase letters
print(df["Name"])

0          ali
1        ahmed
2         sara
3    zain khan
4       fatima
Name: Name, dtype: str

In [53]:
print(df["Phone"])
df["Phone"]=df["Phone"].str.replace("-"," ")      # replace -( hyphon ) with space
df["Phone"]=df["Phone"].str.replace("  "," ")     
print(df["Phone"])

0     0300-1234567
1     0312 9876543
2     0333-5556666
3    0345  1112233
4     0301-9998888
Name: Phone, dtype: str
0    0300 1234567
1    0312 9876543
2    0333 5556666
3    0345 1112233
4    0301 9998888
Name: Phone, dtype: str

In [54]:
print(df["Name"])
df["Name"]=df["Name"].str.capitalize()    # Makes only the first character uppercase
print(df["Name"])

0          ali
1        ahmed
2         sara
3    zain khan
4       fatima
Name: Name, dtype: str
0          Ali
1        Ahmed
2         Sara
3    Zain khan
4       Fatima
Name: Name, dtype: str

In [55]:
df=pd.read_csv('sales_data.csv')

# **Sorting and Ranking data:**

In [56]:
print(df.head())
df_sorted=df.sort_values(["Quantity","Profit"],ascending=[False,True]) # Sort by Quantity in ascd and Profit in desc order.
print(df_sorted.head())

  OrderID   Product     Category     Cost  Quantity  Price  Revenue   Profit  \
0  ORD001    Laptop  Electronics  76500.0         2  85000   170000  17000.0
1  ORD002     Mouse  Accessories   1080.0         5   1200     6000    600.0
2  ORD003  Keyboard  Accessories   2250.0         3   2500     7500    750.0
3  ORD004   Monitor  Electronics  27000.0         1  30000    30000   3000.0
4  ORD005   Printer  Electronics  16200.0         2  18000    36000   3600.0

        City        Date     Month  cost
0    Karachi  2026-01-05   January   NaN
1  Hyderabad  2026-01-08   January   NaN
2     Lahore  2026-01-10   January   NaN
3    Karachi  2026-02-03  February   NaN
4  Islamabad  2026-02-08  February   NaN
   OrderID   Product     Category    Cost  Quantity  Price  Revenue  Profit  \
18  ORD019     Mouse  Accessories  1170.0         7   1300     9100   910.0
7   ORD008     Mouse  Accessories  1080.0         6   1200     7200   720.0
1   ORD002     Mouse  Accessories  1080.0         5   1200     6000   600.0
12  ORD013     Mouse  Accessories  1125.0         5   1250     6250   625.0
19  ORD020  Keyboard  Accessories  2340.0         5   2600    13000  1300.0

         City        Date    Month  cost
18    Karachi  2026-08-01   August   NaN
7      Lahore  2026-03-04    March   NaN
1   Hyderabad  2026-01-08  January   NaN
12     Lahore  2026-05-06      May   NaN
19     Sukkur  2026-08-20   August   NaN

In [57]:
# Calculate Total Revenue per product:
product_revenue = df.groupby("Product")["Revenue"].sum()
print(product_revenue)

Product
Headphones     27400
Keyboard       35900
Laptop        514500
Monitor       180500
Mouse          28550
Printer       109100
Name: Revenue, dtype: int64

In [58]:
# Rank Product on the basis of Revenue genrated by it:
product_rank = product_revenue.rank(method="dense", ascending=False)
print(product_rank)

Product
Headphones    6.0
Keyboard      4.0
Laptop        1.0
Monitor       2.0
Mouse         5.0
Printer       3.0
Name: Revenue, dtype: float64

In [59]:
print(type(product_rank))

<class 'pandas.Series'>

In [60]:
# Add rank as a column of data frame:
df["rank_profit"] = df["Product"].map(
    product_revenue.rank(method="dense", ascending=False)
)
print(df.head(10))

  OrderID     Product     Category     Cost  Quantity  Price  Revenue  \
0  ORD001      Laptop  Electronics  76500.0         2  85000   170000
1  ORD002       Mouse  Accessories   1080.0         5   1200     6000
2  ORD003    Keyboard  Accessories   2250.0         3   2500     7500
3  ORD004     Monitor  Electronics  27000.0         1  30000    30000
4  ORD005     Printer  Electronics  16200.0         2  18000    36000
5  ORD006      Laptop  Electronics  78300.0         1  87000    87000
6  ORD007  Headphones  Accessories   4050.0         4   4500    18000
7  ORD008       Mouse  Accessories   1080.0         6   1200     7200
8  ORD009    Keyboard  Accessories   2340.0         2   2600     5200
9  ORD010     Monitor  Electronics  26550.0         3  29500    88500

    Profit       City        Date     Month  cost  rank_profit
0  17000.0    Karachi  2026-01-05   January   NaN          1.0
1    600.0  Hyderabad  2026-01-08   January   NaN          5.0
2    750.0     Lahore  2026-01-10   January   NaN          4.0
3   3000.0    Karachi  2026-02-03  February   NaN          2.0
4   3600.0  Islamabad  2026-02-08  February   NaN          3.0
5   8700.0    Karachi  2026-02-15  February   NaN          1.0
6   1800.0  Hyderabad  2026-03-01     March   NaN          6.0
7    720.0     Lahore  2026-03-04     March   NaN          5.0
8    520.0     Sukkur  2026-03-10     March   NaN          4.0
9   8850.0  Islamabad  2026-04-02     April   NaN          2.0

# **Merging and joining DataFrames:**

In [61]:
Customer={
    "OrderID":["ORD001","ORD003","ORD004","ORD006","ORD0010"],
    "Nmae":["Naimullah","Sanaullah","Nabi Bux","M Khan","Raja"]}
Customer_info=pd.DataFrame(Customer)
print(Customer_info)

   OrderID       Nmae
0   ORD001  Naimullah
1   ORD003  Sanaullah
2   ORD004   Nabi Bux
3   ORD006     M Khan
4  ORD0010       Raja

In [62]:
df_inner=pd.merge(Customer_info,df, on ="OrderID",how="inner") # retrun common record in both data frames

In [63]:
print(df_inner)

  OrderID       Nmae   Product     Category     Cost  Quantity  Price  \
0  ORD001  Naimullah    Laptop  Electronics  76500.0         2  85000
1  ORD003  Sanaullah  Keyboard  Accessories   2250.0         3   2500
2  ORD004   Nabi Bux   Monitor  Electronics  27000.0         1  30000
3  ORD006     M Khan    Laptop  Electronics  78300.0         1  87000

   Revenue   Profit     City        Date     Month  cost  rank_profit
0   170000  17000.0  Karachi  2026-01-05   January   NaN          1.0
1     7500    750.0   Lahore  2026-01-10   January   NaN          4.0
2    30000   3000.0  Karachi  2026-02-03  February   NaN          2.0
3    87000   8700.0  Karachi  2026-02-15  February   NaN          1.0

In [64]:
df_left=pd.merge(Customer_info,df, on ="OrderID",how="left") # return complete record of left df (Customer) and common record of df.
print(df_left)

   OrderID       Nmae   Product     Category     Cost  Quantity    Price  \
0   ORD001  Naimullah    Laptop  Electronics  76500.0       2.0  85000.0
1   ORD003  Sanaullah  Keyboard  Accessories   2250.0       3.0   2500.0
2   ORD004   Nabi Bux   Monitor  Electronics  27000.0       1.0  30000.0
3   ORD006     M Khan    Laptop  Electronics  78300.0       1.0  87000.0
4  ORD0010       Raja       NaN          NaN      NaN       NaN      NaN

    Revenue   Profit     City        Date     Month  cost  rank_profit
0  170000.0  17000.0  Karachi  2026-01-05   January   NaN          1.0
1    7500.0    750.0   Lahore  2026-01-10   January   NaN          4.0
2   30000.0   3000.0  Karachi  2026-02-03  February   NaN          2.0
3   87000.0   8700.0  Karachi  2026-02-15  February   NaN          1.0
4       NaN      NaN      NaN         NaN       NaN   NaN          NaN

# **Concatination:**

In [65]:
Customer={
    "OrderID":["ORD0020","ORD0023","ORD0050","ORD0030","ORD00100"],
    "Nmae":["Yar M","Kalimullah","Jahangeer","Waqar Ahmed","Sarfaraz"]}
Customer_info2=pd.DataFrame(Customer)

In [66]:
df_concat=pd.concat([Customer_info,Customer_info2])
print(df_concat)

    OrderID         Nmae
0    ORD001    Naimullah
1    ORD003    Sanaullah
2    ORD004     Nabi Bux
3    ORD006       M Khan
4   ORD0010         Raja
0   ORD0020        Yar M
1   ORD0023   Kalimullah
2   ORD0050    Jahangeer
3   ORD0030  Waqar Ahmed
4  ORD00100     Sarfaraz

# **Applying Functions:**
✔ ***apply()***

✔ ***map()***

✔ ***pipe()***

In [67]:
df=pd.read_csv('ecommerce_sales_analytics_5000.csv',parse_dates=["order_date"])
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[us]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(4), str(3)
memory usage: 549.6 KB
None

In [68]:
# map():
df["payment_type"]=df["payment_method"].map({
    "Card":"Digital",
    "Wallet":"Digital",
    "COD":"Cash"})

In [69]:
# verify:
df["payment_type"].unique()

<ArrowStringArray>
['Digital', 'Cash']
Length: 2, dtype: str

In [70]:
print(df[["payment_method","payment_type"]].head(5))

  payment_method payment_type
0         Wallet      Digital
1           Card      Digital
2            COD         Cash
3         Wallet      Digital
4         Wallet      Digital

In [71]:
df.groupby("payment_type").size()    # return total pyment type count

payment_type
Cash       1774
Digital    3226
dtype: int64

In [72]:
# apply():
def revenue_category(row):
    if row["revenue"] > 500:
        return "High"
    elif row["revenue"] >=200:
        return "Medium"
    else:
        return "Low"
df["revenue_category"]=df.apply(revenue_category,axis=1)

In [73]:
# verify:
df["revenue_category"].value_counts()

revenue_category
High      3252
Medium    1098
Low        650
Name: count, dtype: int64

In [74]:
# pipe():
def add_profit(data):
    data["Profit"]=data["revenue"] * 0.2
    return data
def add_net_revenue(data):
    data["net_revenue"]=data["revenue"] - data["Profit"]
    return data
df=(
    df
    .pipe(add_profit)
    .pipe(add_net_revenue)
)

In [75]:
# verify:
df[["revenue","Profit","net_revenue"]].head()

   revenue   Profit  net_revenue
0  1883.20  376.640     1506.560
1   304.10   60.820      243.280
2   644.35  128.870      515.480
3  2569.90  513.980     2055.920
4   468.56   93.712      374.848

# **EDA (Exploratory Data Analysis):**
***EDA is the process of examining and understanding a dataset before doing further analysis or building a machine-learning model.***

# **EDA helps us to:**
✔ ***Look at the data***

✔ ***Understand its structure***

✔ ***Find missing values***

✔ ***Find duplicates***

✔ ***Understand numerical data***

# **Statistical Analysis:**

In [76]:
# shape of data: (no of rows and columns)
print(df.shape)

(5000, 16)

In [77]:
# statistical summary:
df.describe()

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue,Profit,net_revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148,204.391030,817.564118
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000,2.242000,8.968000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500,70.905500,283.622000
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000,159.330000,637.320000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000,303.138000,1212.552000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000,823.866000,3295.464000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219,165.116844,660.467375

In [78]:
df[["unit_price","revenue"]].describe() # for revenue values

        unit_price      revenue
count  5000.000000  5000.000000
mean    308.418774  1021.955148
std     169.259369   825.584219
min      15.150000    11.210000
25%     161.895000   354.527500
50%     309.890000   796.650000
75%     455.557500  1515.690000
max     599.960000  4119.330000

In [79]:
# Quantiles:
df["revenue"].quantile([0.25,0.5,0.75])

0.25     354.5275
0.50     796.6500
0.75    1515.6900
Name: revenue, dtype: float64

In [80]:
# identifying skewness
df["revenue"].mean(),df["revenue"].median()

(np.float64(1021.955148), np.float64(796.65))

In [81]:
df["revenue"].skew() # positive value right skew

np.float64(1.0017064603000962)

In [82]:
# Category_wise descriptive analysis:
df.groupby("product_category")["revenue"].describe() # Do different product category behave different?

,count,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,
Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [83]:
max(df.groupby("product_category")["revenue"].mean()) # find highest category

1059.2819917012448

# **IQR (Inter Quartile Range):**
***IQR is the difference between the third quartile (Q3) and first quartile (Q1), representing the spread of the middle 50% of data.***

In [84]:
Q1 = df["revenue"].quantile(0.25)
Q3 = df["revenue"].quantile(0.75)
IQR = Q3 - Q1
Q1,Q3,IQR

(np.float64(354.5275), np.float64(1515.69), np.float64(1161.1625000000001))

# **Working with Date_time and Time Series Data:**

In [85]:
_df=df.set_index("order_date")

In [86]:
_df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2035-08-31', '2035-09-01', '2035-09-02', '2035-09-03',
               '2035-09-04', '2035-09-05', '2035-09-06', '2035-09-07',
               '2035-09-08', '2035-09-09'],
              dtype='datetime64[us]', name='order_date', length=5000, freq=None)

In [87]:
print(df["order_date"].dtype)

datetime64[us]

In [88]:
# Monthly revenue Analysis:
monthly_revenue=_df["revenue"].resample("ME").sum()
monthly_revenue

order_date
2022-01-31    35624.89
2022-02-28    29908.89
2022-03-31    30309.28
2022-04-30    30781.96
2022-05-31    41629.24
                ...
2035-05-31    33393.87
2035-06-30    25205.26
2035-07-31    23944.48
2035-08-31    29354.74
2035-09-30     4952.23
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [89]:
monthly_revenue.index.is_monotonic_increasing # verify that is date gradualy increasing or not.

True

In [90]:
# Check either monthly_revenue sum is greater than total revenue 
print(monthly_revenue.sum(),df["revenue"].sum())
monthly_revenue.sum() <= df["revenue"].sum()   # check

5109775.74 5109775.74

np.True_

# **Outlier:**
***Outliers are that values which are unusualy far away from normal values or out of lower and upper range.***

# **Outlier Detection using Statistical Rules:**

In [92]:
# find lower and upper:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
lower_bound,upper_bound

(np.float64(-1387.2162500000002), np.float64(3257.43375))

In [96]:
outliers_iqr=df[(df["revenue"] < lower_bound) | (df["revenue"] > upper_bound)]
outliers_iqr.shape

(67, 16)

In [97]:
outliers_iqr[["revenue","product_category"]].head()

     revenue product_category
39   3640.56             Home
69   3338.37           Beauty
102  3449.50         Clothing
126  3472.39         Clothing
157  3917.54      Electronics

In [98]:
# Clean dataSet by removing outliers:
df=df[(df["revenue"]>=lower_bound) & (df["revenue"]<=upper_bound)]
df.shape

(4933, 16)

# **What is a Z-score?**

***A Z-score tells us how far a value is from the mean, measured in terms of standard deviations.***

In [100]:
from scipy.stats import zscore
df=pd.read_csv('ecommerce_sales_analytics_5000.csv',parse_dates=["order_date"])
df["revenue_z"]= zscore(df["revenue"])
outliers_z = df[df["revenue_z"].abs()>3]
outliers_z.shape

(26, 13)

In [101]:
df=df[df["revenue_z"].abs()<=3]
df.shape

(4974, 13)

# **Correlation and Covariance Analysis:**

***Measures the relationship between numberical variables.***

In [103]:
numeric_df=df[["quantity","unit_price","discount","delivery_days","revenue"]]
# Covariance Matrix:
print("\nCovarianc:\n",numeric_df.cov())

# Correlation Matrix:
print("\nCorrelation:\n",numeric_df.corr())

Covarianc:
                   quantity    unit_price  discount  delivery_days  \
quantity          4.057453     -3.554419  0.001031      -0.054180
unit_price       -3.554419  28434.609259  0.395646       8.522237
discount          0.001031      0.395646  0.010247      -0.000194
delivery_days    -0.054180      8.522237 -0.000194       9.932649
revenue        1002.959663  91454.701455 -9.922703      15.784138

                     revenue
quantity         1002.959663
unit_price      91454.701455
discount           -9.922703
delivery_days      15.784138
revenue        645471.483818

Correlation:
                quantity  unit_price  discount  delivery_days   revenue
quantity       1.000000   -0.010464  0.005057      -0.008534  0.619752
unit_price    -0.010464    1.000000  0.023178       0.016036  0.675062
discount       0.005057    0.023178  1.000000      -0.000607 -0.122006
delivery_days -0.008534    0.016036 -0.000607       1.000000  0.006234
revenue        0.619752    0.675062 -0.122006       0.006234  1.000000

In [106]:
# Sort correlation of revenue with other numeric columns:
numeric_df.corr()["revenue"].sort_values(ascending=False)

revenue          1.000000
unit_price       0.675062
quantity         0.619752
delivery_days    0.006234
discount        -0.122006
Name: revenue, dtype: float64

# **Creating an Exploratory Data Analysis (EDA) Report:**